### PR TITLE
Fix git permissions issue

### PR DESCRIPTION
**Pull request by carl-printreleaf**
Changes in Git v2.35.2 cause permissions issue for reviewdog actions

ref: https://github.com/reviewdog/reviewdog/issues/1158

### CODE REVIEW

**Comment by carl-printreleaf** [comment]
Also includes changes requested by reviewdog #2

**Comment by DanMegaGamer** [comment]
This is great, we're also dealing with the same issue.

**Comment by carl-printreleaf** [comment]
@DanMegaGamer I was able to get around the issue by running `chown` after checkout and before standardrb. Hopefully that helps you for now.
```yml
name: reviewdog
on: [pull_request]
jobs:
  standardrb:
    name: standardrb
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - run: sudo chown -R root:root $GITHUB_WORKSPACE
      - name: standardrb
        uses: SennaLabs/action-standardrb@v0.0.6
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review # Default is github-pr-check
          rubocop_version: 1.0.1
          rubocop_flags: --format progress
```

**Comment by DanMegaGamer** [comment]
@carl-printreleaf Thanks, that's really helpful 👍🏼

**Comment by adrianthedev** [comment]
Thanks @carl-printreleaf!

**Comment by carl-printreleaf** [comment]
bump on the review

**Pull request closed without merging**
